// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: cloudguardian.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfrastructureResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EstimatedCost float64                `protobuf:"fixed64,5,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsPublic      bool                   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfrastructureResource) Reset() {
	*x = InfrastructureResource{}
	mi := &file_cloudguardian_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfrastructureResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureResource) ProtoMessage() {}

func (x *InfrastructureResource) ProtoReflect() protoreflect.Message {
	mi := &file_cloudguardian_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureResource.ProtoReflect.Descriptor instead.
func (*InfrastructureResource) Descriptor() ([]byte, []int) {
	return file_cloudguardian_proto_rawDescGZIP(), []int{0}
}

func (x *InfrastructureResource) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *InfrastructureResource) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *InfrastructureResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InfrastructureResource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InfrastructureResource) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *InfrastructureResource) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InfrastructureResource) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type PIIResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResourceId      string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	DataType        string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Confidence      float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	OccurrenceCount int32                  `protobuf:"varint,4,opt,name=occurrence_count,json=occurrenceCount,proto3" json:"occurrence_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PIIResult) Reset() {
	*x = PIIResult{}
	mi := &file_cloudguardian_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PIIResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PIIResult) ProtoMessage() {}

func (x *PIIResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloudguardian_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PIIResult.ProtoReflect.Descriptor instead.
func (*PIIResult) Descriptor() ([]byte, []int) {
	return file_cloudguardian_proto_rawDescGZIP(), []int{1}
}

func (x *PIIResult) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *PIIResult) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *PIIResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PIIResult) GetOccurrenceCount() int32 {
	if x != nil {
		return x.OccurrenceCount
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_cloudguardian_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloudguardian_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_cloudguardian_proto_rawDescGZIP(), []int{2}
}

func (x *ScanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cloudguardian_proto protoreflect.FileDescriptor

const file_cloudguardian_proto_rawDesc = "" +
	"\n" +
	"\x13cloudguardian.proto\x12\rcloudguardian\"\xb9\x03\n" +
	"\x16InfrastructureResource\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12O\n" +
	"\bmetadata\x18\x04 \x03(\v23.cloudguardian.InfrastructureResource.MetadataEntryR\bmetadata\x12%\n" +
	"\x0eestimated_cost\x18\x05 \x01(\x01R\restimatedCost\x12C\n" +
	"\x04tags\x18\x06 \x03(\v2/.cloudguardian.InfrastructureResource.TagsEntryR\x04tags\x12\x1b\n" +
	"\tis_public\x18\a \x01(\bR\bisPublic\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\tPIIResult\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12)\n" +
	"\x10occurrence_count\x18\x04 \x01(\x05R\x0foccurrenceCount\"B\n" +
	"\fScanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb1\x01\n" +
	"\x0eScannerService\x12T\n" +
	"\x0eReportResource\x12%.cloudguardian.InfrastructureResource\x1a\x1b.cloudguardian.ScanResponse\x12I\n" +
	"\x10ReportPIIFinding\x12\x18.cloudguardian.PIIResult\x1a\x1b.cloudguardian.ScanResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_cloudguardian_proto_rawDescOnce sync.Once
	file_cloudguardian_proto_rawDescData []byte
)

func file_cloudguardian_proto_rawDescGZIP() []byte {
	file_cloudguardian_proto_rawDescOnce.Do(func() {
		file_cloudguardian_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloudguardian_proto_rawDesc), len(file_cloudguardian_proto_rawDesc)))
	})
	return file_cloudguardian_proto_rawDescData
}

var file_cloudguardian_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cloudguardian_proto_goTypes = []any{
	(*InfrastructureResource)(nil), // 0: cloudguardian.InfrastructureResource
	(*PIIResult)(nil),              // 1: cloudguardian.PIIResult
	(*ScanResponse)(nil),           // 2: cloudguardian.ScanResponse
	nil,                            // 3: cloudguardian.InfrastructureResource.MetadataEntry
	nil,                            // 4: cloudguardian.InfrastructureResource.TagsEntry
}
var file_cloudguardian_proto_depIdxs = []int32{
	3, // 0: cloudguardian.InfrastructureResource.metadata:type_name -> cloudguardian.InfrastructureResource.MetadataEntry
	4, // 1: cloudguardian.InfrastructureResource.tags:type_name -> cloudguardian.InfrastructureResource.TagsEntry
	0, // 2: cloudguardian.ScannerService.ReportResource:input_type -> cloudguardian.InfrastructureResource
	1, // 3: cloudguardian.ScannerService.ReportPIIFinding:input_type -> cloudguardian.PIIResult
	2, // 4: cloudguardian.ScannerService.ReportResource:output_type -> cloudguardian.ScanResponse
	2, // 5: cloudguardian.ScannerService.ReportPIIFinding:output_type -> cloudguardian.ScanResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cloudguardian_proto_init() }
func file_cloudguardian_proto_init() {
	if File_cloudguardian_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloudguardian_proto_rawDesc), len(file_cloudguardian_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloudguardian_proto_goTypes,
		DependencyIndexes: file_cloudguardian_proto_depIdxs,
		MessageInfos:      file_cloudguardian_proto_msgTypes,
	}.Build()
	File_cloudguardian_proto = out.File
	file_cloudguardian_proto_goTypes = nil
	file_cloudguardian_proto_depIdxs = nil
}
